/*
 * DIO_Config.h
 *
 * Created: 9/6/2026 5:20:17 AM
 *  Author: Sarah
 */ 


#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

#define DIO_PORTA_PIN0_DIR  OUTPUT
#define DIO_PORTA_PIN1_DIR  OUTPUT
#define DIO_PORTA_PIN2_DIR  OUTPUT
#define DIO_PORTA_PIN3_DIR  OUTPUT
#define DIO_PORTA_PIN4_DIR  OUTPUT
#define DIO_PORTA_PIN5_DIR  OUTPUT
#define DIO_PORTA_PIN6_DIR  OUTPUT
#define DIO_PORTA_PIN7_DIR  OUTPUT


#define DIO_PORTB_PIN0_DIR  OUTPUT
#define DIO_PORTB_PIN1_DIR  OUTPUT
#define DIO_PORTB_PIN2_DIR  OUTPUT
#define DIO_PORTB_PIN3_DIR  OUTPUT
#define DIO_PORTB_PIN4_DIR  OUTPUT
#define DIO_PORTB_PIN5_DIR  OUTPUT
#define DIO_PORTB_PIN6_DIR  OUTPUT
#define DIO_PORTB_PIN7_DIR  OUTPUT

#define DIO_PORTC_PIN0_DIR  OUTPUT
#define DIO_PORTC_PIN1_DIR  OUTPUT
#define DIO_PORTC_PIN2_DIR  OUTPUT
#define DIO_PORTC_PIN3_DIR  OUTPUT
#define DIO_PORTC_PIN4_DIR  OUTPUT
#define DIO_PORTC_PIN5_DIR  OUTPUT
#define DIO_PORTC_PIN6_DIR  OUTPUT
#define DIO_PORTC_PIN7_DIR  OUTPUT

#define DIO_PORTD_PIN0_DIR  OUTPUT
#define DIO_PORTD_PIN1_DIR  OUTPUT
#define DIO_PORTD_PIN2_DIR  OUTPUT
#define DIO_PORTD_PIN3_DIR  OUTPUT
#define DIO_PORTD_PIN4_DIR  OUTPUT
#define DIO_PORTD_PIN5_DIR  OUTPUT
#define DIO_PORTD_PIN6_DIR  OUTPUT
#define DIO_PORTD_PIN7_DIR  OUTPUT

#endif /* DIO_CONFIG_H_ */